### ISSUE TITLE
Now libre2.so.8 is too old

### ISSUE THREAD

**Issue by esotericDisciple** [zocker-160/ungoogled-chromium-binaries#1]
...And the jstkdg version uses libicui18n.so.68 which is too new...

**Comment by zocker-160** [comment]
@esotericDisciple yes I know, I am aware of this issue, I will push a new binary ASAP.

I am sorry for not having a binary ready earlier, but I took the last few days off and was not paying attention to Manjaro updates. I apologise.

**Comment by esotericDisciple** [comment]
Oh, okay thanks. Sorry for whining...

**Comment by zocker-160** [comment]
nono all good haha, I keep this issue open until I upload new binary ;)

Happy new year btw :D

**Comment by esotericDisciple** [comment]
Thanks and likewise

**Comment by zocker-160** [comment]
@esotericDisciple  new binary is available

**Comment by zocker-160** [comment]
@esotericDisciple new binary is available

**Comment by neurodiverseEsoteric** [comment]
@zocker-160 New release?

**Comment by zocker-160** [comment]
> @zocker-160 New release?

@neurodiverseEsoteric I am on vacation right now, so please excuse the delayed release, it will be available within 2 hours from now.

**Comment by neurodiverseEsoteric** [comment]
Ok thanks...Sorry I interrupted your vacation...

**Comment by zocker-160** [comment]
no problem @neurodiverseEsoteric, you cannot know it and I am working on fully automating the build, so that ppl get binaries without any manual steps by me.

**Comment by zocker-160** [comment]
new binary is available

**Comment by neurodiverseEsoteric** [comment]
Thanks yet again!
