### ISSUE TITLE
automatic build or personal machine

### ISSUE THREAD

**Issue by micro-elai** [zocker-160/ungoogled-chromium-binaries#2]
her there, thank you for your contribution on making this repo available to the people with weaker hardware, i'm just wondering about the build, do you do it on an automatic build system or is it a personal machine ?

**Comment by zocker-160** [comment]
I am building it on a personal machine using the [aur-builder docker container](https://github.com/zocker-160/aur-builder).

Since I have to build it anyway for personal use, it makes sense to me to share it with others.

**Comment by micro-elai** [comment]
i really appreciate the work that you doing, thank you.
