### ISSUE TITLE
libicui18n.so.70/71.1

### ISSUE THREAD

**Issue by loufee** [zocker-160/ungoogled-chromium-binaries#3]
Hello, a few are running into an issue, myself included, with libicui18n.so.70, now at 71.1. Issue with [#180](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/issues/180) was sorted.

`/usr/lib/chromium/chromium: error while loading shared libraries: libicui18n.so.70: cannot open shared object file: No such file or directory`

**Comment by zocker-160** [comment]
yep I am rebuilding, that should fix it.

**Comment by loufee** [comment]
Many thanks!

**Comment by zocker-160** [comment]
rebuild is available now and fixes this issue
