### ISSUE TITLE
libFLAC.so.8

### ISSUE THREAD

**Issue by de-es** [zocker-160/ungoogled-chromium-binaries#4]
[Stable Update] 2022-10-05 brings libFLAC.so.12, so the latest build wouldn't run:

`/usr/lib/chromium/chromium: error while loading shared libraries: libFLAC.so.8: cannot open shared object file: No such file or directory`

Thanks in advance. Really appreciate your Manjaro builds.

**Comment by zocker-160** [comment]
ah thanks for letting me know, I haven't installed that update yet, so I did not notice.

I will do a rebuild.

**Comment by zocker-160** [comment]
rebuild is now available, sorry for the delay

**Comment by de-es** [comment]
No worries!
